admins_list: []
channel: '-1001847073282'
info: '🔥ВАЖНО🔥

  Шторку игрового поля поднимаем до конца вверх.

  Если игровое поле вдруг будет ездить, то ползунок справа просто опускаем вниз



  1. Бот запускается/ перезапускается кнопкой /start.


  2. В шапке профиля есть ссылка менеджера по всем вопросам, также ему следует отправлять
  баги ( скрин + описание проблемы )


  3. Прежде чем отправить другу ссылку на игру он должен запустить/перезапустить бота,
  подписаться на канал и после этого можете отправлять ( В случае если он не активировал
  у себя бота )


  4. Если вы не завершили игру сдачей, матом или ничьей, то сессию стоит завершить
  по кнопке "выйти из игры"


  "У вас уже начата игра, играйте либо сдайтесь" - появится такое сообщение, под ним
  кнопка "выйти из игры"'
link: ''
link_get_priz: https://stackoverflow.com/
link_help_game: https://stackoverflow.com/questions/18363022/importerror-no-module-named-pip
premium: 500
priz: 1500
token: "BOT_TOKEN"
yookassa_api: "YOOKASSA_API"
yookassa_id: 'YOOKASSA_ID'
utm: {
  youtube: 0
}
DOMEN: 'DOMEN'
dsn: 'DB URL'